server:
  port: 8080
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

api:
  lotto:
    host: https://www.dhlottery.co.kr/common.do

spring:
  main:
    allow-bean-definition-overriding: true