server:
  port: 8080

spring:
  profiles:
    activate: local

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
#    org.hibernate.type: trace 파라미터에 뭐가 들어가는지 찍어줌





